eitri-apps:
    - path: ./_shopping-shopify-template-sdk
      workspace: sdk
      alias: sdk
      focus: false
      shared: true
    - path: ./_shopping-shopify-template-shared
      workspace: shared
      alias: shared
      focus: false
      shared: true
    - path: ./shopping-shopify-template-home
      workspace: home
      alias: home
      focus: true
      shared: false
    - path: ./shopping-shopify-template-pdp
      workspace: pdp
      alias: pdp
      focus: false
      shared: false
    - path: ./shopping-shopify-template-cart
      workspace: cart
      alias: cart
      focus: false
      shared: false
bottom-tab-view-simulation:
    eitri-apps:
        - slug: 'shopping-shopify-template-home'
          title: 'Inicio'
          initialization-params:
              type: 'string'
              value: 'tabIndex=0'
        - slug: "shopping-shopify-template-home"
          title: "Categorias"
          initialization-params:
            type: "string"
            value: "tabIndex=1&route=Categories"
        - slug: 'shopping-shopify-template-cart'
          title: 'Carrinho'
          initialization-params:
              type: 'string'
              value: 'tabIndex=2'
        - slug: "shopping-shopify-template-home"
          title: "Ofertas"
          initialization-params:
            type: "string"
            value: "tabIndex=3&route=ProductCatalog&handle=tech-t-shirt-nossa-camiseta-mais-iconica&type=collection"
        #  - slug: "shopping-vtex-template-account"
        #    title: "Perfil"
        #    initialization-params:
        #      type: "string"
        #      value: "tabIndex=4"

#application-id: cca11cae-342e-4ca6-a955-00abca321d86
#insider
application-id: aaf9891b-c148-40fc-aa68-0a5028153b78
eitri-luminus: "2.22.3"
eitri-bifrost: "4.7.0"